# Don't allow subtitles to be rendered in the margin areas (except for ASS)
sub-use-margins=no

# Youtube-dl
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-format=bv[width<=?4096]+ba/best

# See `mpv --show-profile=high-quality`
profile=high-quality

# Down scale larger video to fit the screen
autofit-larger=100%x100%

[svp]
input-ipc-server=/tmp/mpvsocket     # Receives input from SVP
hr-seek-framedrop=no                # Fixes audio desync
resume-playback=no                  # Not compatible with SVP
