#!/bin/bash
set -euo pipefail

tag=$(basename "$0" | awk -F . '/^toggle-tag.([[:alnum:]][[:alnum:]_-]*)$/ {print $NF}')
[ -n "$tag" ] || {
    printf '%s\n' "No tag name specified. Symlink this script to toggle-tag.<tagname>" >&2
    exit 1
}

is_uuid() {
    [[ ${1-} =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]
}
for uuid in "$@"; do
    is_uuid "${uuid}" || {
        printf '%s\n' "Not a uuid: ${uuid}" >&2
        exit 1
    }
done

for uuid in "$@"; do
    if [ "$(task "${uuid}" +"$tag" count)" == '1' ]; then
        operation="-$tag"
    else
        operation="+$tag"
    fi

    task \
        rc.verbose=nothing \
        rc.bulk=0 \
        rc.confirmation=off \
        rc.dependency.confirmation=off \
        rc.recurrence.confirmation=off \
        "$uuid" modify "$operation"
done
