[window]
decorations_theme_variant = "Dark"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.footer_bar]
background = "#a89984"
foreground = "#1d2021"

[colors.line_indicator]
background = "#a89984"
foreground = "#1d2021"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#b16286"
foreground = "#282828"

[colors.search.matches]
background = "#d79921"
foreground = "#282828"

[colors.cursor]
text = "#282828"
cursor = "#ebdbb2"
